### ISSUE TITLE
Unable to install in Mac 10.14.2 Python: 2.7.10

### ISSUE THREAD

**Issue by riz-hossain** [asweigart/PyGetWindow#12]
Hello I am using a clean Mac OS which by default comes with python 2.7.10.
Below is the error message that I am getting:

Collecting PyGetWindow
  Using cached https://files.pythonhosted.org/packages/8c/95/d401a85c5e9a40fac545708961b38beb5a71c9a8fc607de30d31f03de17e/PyGetWindow-0.0.5.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-oWj25I/PyGetWindow/setup.py", line 10, in <module>
        with open('README.md', 'r', encoding='utf-8') as fh:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-oWj25I/PyGetWindow/

**Comment by lukaszgo1** [comment]
@riz-hossain This one should be fixed with recent version on PyPI. Can you confirm?

**Comment by riz-hossain** [comment]
@lukaszgo1 , thank you for the reply.  I had installed it by easy_install from the same package directly. I will uninstall it and try with pip installer later today and get back.
