### ISSUE TITLE
Cannot install the package by pip due to some encoding error

### ISSUE THREAD

**Issue by saulshao** [asweigart/PyGetWindow#2]
When I try to install the package via pip command, it generates the following error message:

Collecting pygetwindow (from pyautogui)
  Downloading https://files.pythonhosted.org/packages/f1/54/740939161eb3471e8f775ce9b0fcac0e54c36bf63501e51f2cd7158f587d/PyGetWindow-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\******\AppData\Local\Temp\pip-install-wflouosi\pygetwindow\setup.py", line 11, in <module>
        long_description = fh.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 905: illegal multibyte sequence

So I tried to modify the setup.py and change the line 11:
Original:
`with open("README.md", "r") as fh:
    long_description = fh.read()
`
New:
`with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()
`

It looks like this change can bypass the issue,

**Comment by jyp0802** [comment]
How do you install with the downloaded (and modified) file? It's not pip install ... I assume

**Comment by zhongxiali** [comment]
I got the same error message when install via pip and python 3.7

**Comment by wtysos11** [comment]
I got the same error too, in win10, python3.7. It works fine if you change line 10 in setup.py to `with open("README.md", "r",encoding='UTF-8') as fh:`

**Comment by WangElysion** [comment]
But it is no use on my computer.....I have used python2.7.

**Comment by jtyoui** [comment]
因为要安装pyautogui，结果要先安装依赖PyGetWindow，然后pip install PyGetWindow报错。
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 905: illegal multibyte sequence
我下载源码修改setup.py，将with open("README.md", "r") 修改成 with open("README.md", "r", encoding="utf-8")。
使用wheel进行安装即可。
安装命令：
python setup.py bdist_wheel
pip install dist/*

**Comment by syjsxxjy** [comment]
创建不了wheel，想在win7上装，然后发现完全不会用win的python

**Comment by lovedva** [comment]
> 因为要安装pyautogui，结果要先安装依赖PyGetWindow，然后pip install PyGetWindow报错。
> UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 905: illegal multibyte sequence
> 我下载源码修改setup.py，将with open("README.md", "r") 修改成 with open("README.md", "r", encoding="utf-8")。
> 使用wheel进行安装即可。
> 安装命令：
> python setup.py bdist_wheel
> pip install dist/*
创建不了wheel，想在win7上装，然后发现完全不会用win的python

**Comment by jtyoui** [comment]
wheel是第三方库.先要安装.pip install wheel

**Comment by jtyoui** [comment]
> > 因为要安装pyautogui，结果要先安装依赖PyGetWindow，然后pip install PyGetWindow报错。
> > UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 905: illegal multibyte sequence
> > 我下载源码修改setup.py，将with open("README.md", "r") 修改成 with open("README.md", "r", encoding="utf-8")。
> > 使用wheel进行安装即可。
> > 安装命令：
> > python setup.py bdist_wheel
> > pip install dist/*
> > 创建不了wheel，想在win7上装，然后发现完全不会用win的python
wheel是第三方库.先要安装.pip install wheel

**Comment by Crescent-Saturn** [comment]
> 因为要安装pyautogui，结果要先安装依赖PyGetWindow，然后pip install PyGetWindow报错。
> UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 905: illegal multibyte sequence
> 我下载源码修改setup.py，将with open("README.md", "r") 修改成 with open("README.md", "r", encoding="utf-8")。
> 使用wheel进行安装即可。
> 安装命令：
> python setup.py bdist_wheel
> pip install dist/*



谢谢你的方案，完美解决~
我也是安装pyautogui时遇到同样报错，发现是这个库报错，真希望UTF赶紧统一吧。。。
给跪了。。。

**Comment by mrchibbo** [comment]
excellent solustion, thanks!

**Comment by huhuang03** [comment]
> > 因为要安装pyautogui，结果要先安装依赖PyGetWindow，然后pip install PyGetWindow报错。
> > UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 905: illegal multibyte sequence
> > 我下载源码修改setup.py，将with open("README.md", "r") 修改成 with open("README.md", "r", encoding="utf-8")。
> > 使用wheel进行安装即可。
> > 安装命令：
> > python setup.py bdist_wheel
> > pip install dist/*
> 
> 谢谢你的方案，完美解决~
> 我也是安装pyautogui时遇到同样报错，发现是这个库报错，真希望UTF赶紧统一吧。。。
> 给跪了。。。

可以使用pip install -e  项目路径，快捷安装

**Comment by b1llow** [comment]
why not merge? I see it has some pr to fix the problem.

**Comment by alexlausz** [comment]
> 因为要安装pyautogui，结果要先安装依赖PyGetWindow，然后pip install PyGetWindow报错。
> UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 905: illegal multibyte sequence
> 我下载源码修改setup.py，将with open("README.md", "r") 修改成 with open("README.md", "r", encoding="utf-8")。
> 使用wheel进行安装即可。
> 安装命令：
> python setup.py bdist_wheel
> pip install dist/*

我在32位python下用此方法安装pygetwindow版本0.04不行，0.03版本可以
