### ISSUE TITLE
Window.__str__ broken, cant print window

### ISSUE THREAD

**Issue by laundmo** [asweigart/PyGetWindow#28]
```
Traceback (most recent call last):
  File "<stdin>", line 16, in <module>
  File "<stdin>", line 11, in sortwindowlocation
  File "c:\python38\lib\site-packages\pygetwindow\__init__.py", line 71, in __str__
    r = self._getWindowRect(self._hWnd)
TypeError: _getWindowRect() takes 1 positional argument but 2 were given
```

**Comment by ealmloff** [comment]
looking around the source code it looks like this is easily fixed by removing self._hWnd:
https://github.com/asweigart/PyGetWindow/pull/33
